### ISSUE TITLE
Database files missing in repo

### ISSUE THREAD

**Issue by VoeP** [Justinh22/WastesOfValai#3]
Hi, could you include an example .db file for the dungeonDatabase, playerDatabase and roomDatabase so the saving features work correctly? Thanks either way, a big fan of this project by the way! :)

**Comment by Justinh22** [comment]
Hi! All of those databases are generated upon the game being saved (which occurs whenever you enter a haven, one of the points marked by 'H'). I believe there may be a bug in the current version (v0.2) that you may be running into, but the v0.3 branch should be stable in that regard. 

Thanks for reaching out! I didn't expect this to get any attention, as it's a just a small pet project of mine, but I'm glad you like it!
